{% set name = "hummingbird-ml" %}
{% set version = "0.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hummingbird-ml-{{ version }}.tar.gz
  sha256: a0cfc716977f45708d49bc0b0903e375cc150d338e52d4703c3b7cf809f0085e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - dill
    - numpy >=1.15,<=1.19.4
    - onnxconverter-common >=1.6.0,<=1.7.0
    - psutil
    - python >=3.6
    - scikit-learn >=0.21.3,<=0.23.2
    - scipy <=1.5.4
    - pytorch >=1.4.*,<=1.8.0

test:
  imports:
    - hummingbird.ml
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/hummingbird
  summary: Convert trained traditional machine learning models into tensor computations
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
