{% set name = "hummingbird-ml" %}
{% set version = "0.4.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hummingbird-ml-{{ version }}.tar.gz
  sha256: 215680c8dc85c7938e6fd7ac30b79df2248caa58ee77d7ba9f77e9ca72222715

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - dill 
    - numpy >=1.15
    - onnxconverter-common >=1.6.0
    - psutil 
    - python >=3.6
    - scikit-learn >=0.21.3
    - scipy 
    - pytorch >=1.4
    
test:
  imports:
    - hummingbird.ml
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/hummingbird
  summary: Convert trained traditional machine learning models into tensor computations
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
